import { Contract, type BrowserProvider, type Signer } from "ethers";

export interface Deployment {
  network: string;
  chainId: number;
  snd: string;
  release: string;
  timelock: string;
  governor: string;
}

const DEFAULT_DEPLOYMENT: Deployment = {
  network: "base",
  chainId: 8453,
  snd: "0x0000000000000000000000000000000000000000",
  release: "0x0000000000000000000000000000000000000000",
  timelock: "0x0000000000000000000000000000000000000000",
  governor: "0x0000000000000000000000000000000000000000",
};

let _cache: Deployment | null = null;

export async function getDeployment(): Promise<Deployment> {
  if (_cache) return _cache;
  try {
    const res = await fetch("/contracts.json", { cache: "no-store" });
    if (res.ok) {
      const d: Deployment = { ...DEFAULT_DEPLOYMENT, ...((await res.json()) as Partial<Deployment>) };
      _cache = d;
      return d;
    }
  } catch {
    /* fall through */
  }
  return DEFAULT_DEPLOYMENT;
}

export function isDeployed(d: Deployment): boolean {
  return d.snd.startsWith("0x") && d.snd !== DEFAULT_DEPLOYMENT.snd;
}

// Minimal ABIs (full ones generated by hardhat/typechain are not shipped to the UI)
export const SND_ABI = [
  "function balanceOf(address) view returns (uint256)",
  "function decimals() view returns (uint8)",
  "function symbol() view returns (string)",
  "function approve(address spender, uint256 amount) returns (bool)",
  "function transfer(address to, uint256 amount) returns (bool)",
  "function getVotes(address) view returns (uint256)",
];

export const RELEASE_ABI = [
  "function mintRelease(string name, string metadata, address[] collaborators, uint256[] shares, uint96 royaltyBps) returns (uint256)",
  "function fund(uint256 tokenId) payable",
  "function fundWithSND(uint256 tokenId, uint256 amount)",
  "function claim(uint256 tokenId)",
  "function claimable(uint256, address) view returns (uint256, uint256)",
  "function releaseOf(uint256) view returns (string, string, address[], uint256[], uint256, uint256)",
  "function ownerOf(uint256) view returns (address)",
];

export const GOVERNOR_ABI = [
  "function state(uint256) view returns (uint8)",
  "function proposalSnapshot(uint256) view returns (uint256)",
  "function proposalDeadline(uint256) view returns (uint256)",
  "function proposalCount() view returns (uint256)",
  "function castVote(uint256 proposalId, uint8 support) returns (uint256)",
  "function hasVoted(uint256, address) view returns (bool)",
  "event ProposalCreated(uint256 proposalId, address proposer, address[] targets, uint256[] values, string[] signatures, bytes[] calldatas, uint256 voteStart, uint256 voteEnd, string description)",
];

export async function getSnd(signer: Signer | BrowserProvider, address: string) {
  return new Contract(address, SND_ABI, signer);
}

export async function getRelease(signer: Signer | BrowserProvider, address: string) {
  return new Contract(address, RELEASE_ABI, signer);
}

export async function getGovernor(signer: Signer | BrowserProvider, address: string) {
  return new Contract(address, GOVERNOR_ABI, signer);
}

export function explorerTokenUrl(deployment: Deployment, tokenId: number): string {
  return `https://basescan.org/token/${deployment.release}?a=${tokenId}`;
}

export function explorerAddressUrl(address: string): string {
  return `https://basescan.org/address/${address}`;
}
